[2024-12-28T12:57:47.100+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/retrieve_teams_dag.py
[2024-12-28T12:57:47.101+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/retrieve_teams_dag.py for tasks to queue
[2024-12-28T12:57:47.101+0000] {logging_mixin.py:150} INFO - [2024-12-28T12:57:47.101+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/retrieve_teams_dag.py
[2024-12-28T12:57:47.110+0000] {logging_mixin.py:150} INFO - [2024-12-28T12:57:47.109+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/retrieve_teams_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/retrieve_teams_dag.py", line 4, in <module>
    from nba_api.stats.static import teams
ModuleNotFoundError: No module named 'nba_api'
[2024-12-28T12:57:47.111+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/retrieve_teams_dag.py
[2024-12-28T12:57:47.127+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/retrieve_teams_dag.py took 0.030 seconds
[2024-12-28T12:58:17.431+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/retrieve_teams_dag.py
[2024-12-28T12:58:17.433+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/retrieve_teams_dag.py for tasks to queue
[2024-12-28T12:58:17.434+0000] {logging_mixin.py:150} INFO - [2024-12-28T12:58:17.433+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/retrieve_teams_dag.py
[2024-12-28T12:58:17.441+0000] {logging_mixin.py:150} INFO - [2024-12-28T12:58:17.440+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/retrieve_teams_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/retrieve_teams_dag.py", line 4, in <module>
    from nba_api.stats.static import teams
ModuleNotFoundError: No module named 'nba_api'
[2024-12-28T12:58:17.441+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/retrieve_teams_dag.py
[2024-12-28T12:58:17.474+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/retrieve_teams_dag.py took 0.046 seconds
[2024-12-28T12:58:47.814+0000] {processor.py:157} INFO - Started process (PID=44) to work on /opt/airflow/dags/retrieve_teams_dag.py
[2024-12-28T12:58:47.815+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/retrieve_teams_dag.py for tasks to queue
[2024-12-28T12:58:47.816+0000] {logging_mixin.py:150} INFO - [2024-12-28T12:58:47.816+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/retrieve_teams_dag.py
[2024-12-28T12:58:47.830+0000] {logging_mixin.py:150} INFO - [2024-12-28T12:58:47.829+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/retrieve_teams_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/retrieve_teams_dag.py", line 4, in <module>
    from nba_api.stats.static import teams
ModuleNotFoundError: No module named 'nba_api'
[2024-12-28T12:58:47.831+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/retrieve_teams_dag.py
[2024-12-28T12:58:47.856+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/retrieve_teams_dag.py took 0.046 seconds
