[2025-01-20T14:38:48.646+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_historical_data_pipeline.ingest_season_games manual__2025-01-20T14:38:46.578075+00:00 [queued]>
[2025-01-20T14:38:48.666+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_historical_data_pipeline.ingest_season_games manual__2025-01-20T14:38:46.578075+00:00 [queued]>
[2025-01-20T14:38:48.669+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2025-01-20T14:38:48.710+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): ingest_season_games> on 2025-01-20 14:38:46.578075+00:00
[2025-01-20T14:38:48.720+0000] {standard_task_runner.py:57} INFO - Started process 453 to run task
[2025-01-20T14:38:48.731+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nba_historical_data_pipeline', 'ingest_season_games', 'manual__2025-01-20T14:38:46.578075+00:00', '--job-id', '1032', '--raw', '--subdir', 'DAGS_FOLDER/app_start_ns.py', '--cfg-path', '/tmp/tmpi71lxqrz']
[2025-01-20T14:38:48.734+0000] {standard_task_runner.py:85} INFO - Job 1032: Subtask ingest_season_games
[2025-01-20T14:38:48.872+0000] {task_command.py:410} INFO - Running <TaskInstance: nba_historical_data_pipeline.ingest_season_games manual__2025-01-20T14:38:46.578075+00:00 [running]> on host 4e77ceae0c87
[2025-01-20T14:38:49.016+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_historical_data_pipeline' AIRFLOW_CTX_TASK_ID='ingest_season_games' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T14:38:46.578075+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-20T14:38:46.578075+00:00'
[2025-01-20T14:38:49.017+0000] {app_start_ns.py:111} INFO - Starting Kafka producer for season games...
[2025-01-20T14:40:35.896+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-01-20T14:40:35.901+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 453. PIDs of all processes in the group: [455, 453]
[2025-01-20T14:40:35.902+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 453
[2025-01-20T14:40:35.912+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-20T14:40:35.940+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=455, status='terminated', started='14:38:48') (455) terminated with exit code None
[2025-01-20T14:40:36.122+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=453, status='terminated', exitcode=0, started='14:38:48') (453) terminated with exit code 0
