[2025-01-08T06:30:44.143+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_historical_data_pipeline.ingest_season_games manual__2025-01-08T06:30:35.022635+00:00 [queued]>
[2025-01-08T06:30:44.149+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_historical_data_pipeline.ingest_season_games manual__2025-01-08T06:30:35.022635+00:00 [queued]>
[2025-01-08T06:30:44.149+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2025-01-08T06:30:44.158+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): ingest_season_games> on 2025-01-08 06:30:35.022635+00:00
[2025-01-08T06:30:44.161+0000] {standard_task_runner.py:57} INFO - Started process 390 to run task
[2025-01-08T06:30:44.163+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nba_historical_data_pipeline', 'ingest_season_games', 'manual__2025-01-08T06:30:35.022635+00:00', '--job-id', '550', '--raw', '--subdir', 'DAGS_FOLDER/app_start_ns.py', '--cfg-path', '/tmp/tmpjlvwmbk6']
[2025-01-08T06:30:44.164+0000] {standard_task_runner.py:85} INFO - Job 550: Subtask ingest_season_games
[2025-01-08T06:30:44.194+0000] {task_command.py:410} INFO - Running <TaskInstance: nba_historical_data_pipeline.ingest_season_games manual__2025-01-08T06:30:35.022635+00:00 [running]> on host 39b6821e1f43
[2025-01-08T06:30:44.243+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_historical_data_pipeline' AIRFLOW_CTX_TASK_ID='ingest_season_games' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T06:30:35.022635+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-08T06:30:35.022635+00:00'
[2025-01-08T06:31:49.860+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-01-08T06:31:49.865+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 390. PIDs of all processes in the group: [391, 390]
[2025-01-08T06:31:49.865+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 390
[2025-01-08T06:31:49.867+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-08T06:31:49.966+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=390, status='terminated', exitcode=0, started='06:30:43') (390) terminated with exit code 0
[2025-01-08T06:31:49.967+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=391, status='terminated', started='06:30:43') (391) terminated with exit code None
