[2025-01-07T13:18:56.687+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.spark_csv_to_postgres_teams manual__2025-01-07T13:13:43.323182+00:00 [queued]>
[2025-01-07T13:18:56.715+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.spark_csv_to_postgres_teams manual__2025-01-07T13:13:43.323182+00:00 [queued]>
[2025-01-07T13:18:56.715+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 4
[2025-01-07T13:18:56.750+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_csv_to_postgres_teams> on 2025-01-07 13:13:43.323182+00:00
[2025-01-07T13:18:56.758+0000] {standard_task_runner.py:57} INFO - Started process 58 to run task
[2025-01-07T13:18:56.764+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'spark_csv_to_postgres_teams', 'manual__2025-01-07T13:13:43.323182+00:00', '--job-id', '388', '--raw', '--subdir', 'DAGS_FOLDER/app_start.py', '--cfg-path', '/tmp/tmpx5ftqzm3']
[2025-01-07T13:18:56.769+0000] {standard_task_runner.py:85} INFO - Job 388: Subtask spark_csv_to_postgres_teams
[2025-01-07T13:18:56.872+0000] {task_command.py:410} INFO - Running <TaskInstance: nba_data_pipeline.spark_csv_to_postgres_teams manual__2025-01-07T13:13:43.323182+00:00 [running]> on host dbef3e6b2587
[2025-01-07T13:18:57.091+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='spark_csv_to_postgres_teams' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T13:13:43.323182+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T13:13:43.323182+00:00'
[2025-01-07T13:18:57.111+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2025-01-07T13:18:57.115+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master spark-master:7077 --conf spark.executor.extraJavaOptions=-Dlog4j.configuration=log4j.properties --conf spark.driverEnv.SPARK_HOME=/opt/spark --conf spark.executorEnv.SPARK_HOME=/opt/spark --conf spark.driverEnv.PATH=/opt/spark/bin:/usr/local/bin:/usr/bin:$PATH --conf spark.executorEnv.PATH=/opt/spark/bin:/usr/local/bin:/usr/bin:$PATH --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.4,org.postgresql:postgresql:42.6.0 --executor-memory 2G --driver-memory 1G --name Spark Csv To Postgres Teams --queue root.default --deploy-mode client /opt/***/include/scripts/spark_csv_to_postgres_teams.py
[2025-01-07T13:18:57.156+0000] {spark_submit.py:490} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-01-07T13:19:01.306+0000] {spark_submit.py:490} INFO - :: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-01-07T13:19:01.420+0000] {spark_submit.py:490} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-01-07T13:19:01.421+0000] {spark_submit.py:490} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-01-07T13:19:01.425+0000] {spark_submit.py:490} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-01-07T13:19:01.427+0000] {spark_submit.py:490} INFO - org.postgresql#postgresql added as a dependency
[2025-01-07T13:19:01.428+0000] {spark_submit.py:490} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-ec728876-de14-48aa-bc55-751e17d813eb;1.0
[2025-01-07T13:19:01.428+0000] {spark_submit.py:490} INFO - confs: [default]
[2025-01-07T13:19:04.046+0000] {spark_submit.py:490} INFO - found org.postgresql#postgresql;42.6.0 in central
[2025-01-07T13:19:04.292+0000] {spark_submit.py:490} INFO - found org.checkerframework#checker-qual;3.31.0 in central
[2025-01-07T13:19:04.383+0000] {spark_submit.py:490} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar ...
[2025-01-07T13:19:05.003+0000] {spark_submit.py:490} INFO - [SUCCESSFUL ] org.postgresql#postgresql;42.6.0!postgresql.jar (705ms)
[2025-01-07T13:19:05.093+0000] {spark_submit.py:490} INFO - downloading https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.jar ...
[2025-01-07T13:19:05.238+0000] {spark_submit.py:490} INFO - [SUCCESSFUL ] org.checkerframework#checker-qual;3.31.0!checker-qual.jar (229ms)
[2025-01-07T13:19:05.241+0000] {spark_submit.py:490} INFO - :: resolution report :: resolve 2871ms :: artifacts dl 940ms
[2025-01-07T13:19:05.245+0000] {spark_submit.py:490} INFO - :: modules in use:
[2025-01-07T13:19:05.248+0000] {spark_submit.py:490} INFO - org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-01-07T13:19:05.256+0000] {spark_submit.py:490} INFO - org.postgresql#postgresql;42.6.0 from central in [default]
[2025-01-07T13:19:05.265+0000] {spark_submit.py:490} INFO - ---------------------------------------------------------------------
[2025-01-07T13:19:05.270+0000] {spark_submit.py:490} INFO - |                  |            modules            ||   artifacts   |
[2025-01-07T13:19:05.273+0000] {spark_submit.py:490} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-01-07T13:19:05.275+0000] {spark_submit.py:490} INFO - ---------------------------------------------------------------------
[2025-01-07T13:19:05.280+0000] {spark_submit.py:490} INFO - |      default     |   3   |   2   |   2   |   0   ||   2   |   2   |
[2025-01-07T13:19:05.281+0000] {spark_submit.py:490} INFO - ---------------------------------------------------------------------
[2025-01-07T13:19:05.283+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.283+0000] {spark_submit.py:490} INFO - :: problems summary ::
[2025-01-07T13:19:05.285+0000] {spark_submit.py:490} INFO - :::: WARNINGS
[2025-01-07T13:19:05.286+0000] {spark_submit.py:490} INFO - problem while downloading module descriptor: https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.4/spark-sql-kafka-0-10_2.12-3.5.4.pom: Downloaded file size (0) doesn't match expected Content Length (14706) for https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.4/spark-sql-kafka-0-10_2.12-3.5.4.pom. Please retry. (237ms)
[2025-01-07T13:19:05.287+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.288+0000] {spark_submit.py:490} INFO - module not found: org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.4
[2025-01-07T13:19:05.288+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.289+0000] {spark_submit.py:490} INFO - ==== local-m2-cache: tried
[2025-01-07T13:19:05.290+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.291+0000] {spark_submit.py:490} INFO - file:/home/***/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.4/spark-sql-kafka-0-10_2.12-3.5.4.pom
[2025-01-07T13:19:05.292+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.294+0000] {spark_submit.py:490} INFO - -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.4!spark-sql-kafka-0-10_2.12.jar:
[2025-01-07T13:19:05.294+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.295+0000] {spark_submit.py:490} INFO - file:/home/***/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.4/spark-sql-kafka-0-10_2.12-3.5.4.jar
[2025-01-07T13:19:05.296+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.298+0000] {spark_submit.py:490} INFO - ==== local-ivy-cache: tried
[2025-01-07T13:19:05.299+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.300+0000] {spark_submit.py:490} INFO - /home/***/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.5.4/ivys/ivy.xml
[2025-01-07T13:19:05.301+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.302+0000] {spark_submit.py:490} INFO - -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.4!spark-sql-kafka-0-10_2.12.jar:
[2025-01-07T13:19:05.303+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.304+0000] {spark_submit.py:490} INFO - /home/***/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.5.4/jars/spark-sql-kafka-0-10_2.12.jar
[2025-01-07T13:19:05.304+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.305+0000] {spark_submit.py:490} INFO - ==== central: tried
[2025-01-07T13:19:05.306+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.306+0000] {spark_submit.py:490} INFO - https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.4/spark-sql-kafka-0-10_2.12-3.5.4.pom
[2025-01-07T13:19:05.307+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.307+0000] {spark_submit.py:490} INFO - ==== spark-packages: tried
[2025-01-07T13:19:05.307+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.308+0000] {spark_submit.py:490} INFO - https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.4/spark-sql-kafka-0-10_2.12-3.5.4.pom
[2025-01-07T13:19:05.308+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.309+0000] {spark_submit.py:490} INFO - -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.4!spark-sql-kafka-0-10_2.12.jar:
[2025-01-07T13:19:05.309+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.310+0000] {spark_submit.py:490} INFO - https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.4/spark-sql-kafka-0-10_2.12-3.5.4.jar
[2025-01-07T13:19:05.310+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.311+0000] {spark_submit.py:490} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2025-01-07T13:19:05.311+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.312+0000] {spark_submit.py:490} INFO - ::          UNRESOLVED DEPENDENCIES         ::
[2025-01-07T13:19:05.312+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.313+0000] {spark_submit.py:490} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2025-01-07T13:19:05.313+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.314+0000] {spark_submit.py:490} INFO - :: org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.4: not found
[2025-01-07T13:19:05.314+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.315+0000] {spark_submit.py:490} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2025-01-07T13:19:05.315+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.315+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.316+0000] {spark_submit.py:490} INFO - 
[2025-01-07T13:19:05.316+0000] {spark_submit.py:490} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-01-07T13:19:05.317+0000] {spark_submit.py:490} INFO - Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.4: not found]
[2025-01-07T13:19:05.318+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1613)
[2025-01-07T13:19:05.318+0000] {spark_submit.py:490} INFO - at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-01-07T13:19:05.319+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:339)
[2025-01-07T13:19:05.320+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:969)
[2025-01-07T13:19:05.321+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:199)
[2025-01-07T13:19:05.322+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:222)
[2025-01-07T13:19:05.322+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2025-01-07T13:19:05.322+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1125)
[2025-01-07T13:19:05.323+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1134)
[2025-01-07T13:19:05.323+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-01-07T13:19:05.376+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-master:7077 --conf spark.executor.extraJavaOptions=-Dlog4j.configuration=log4j.properties --conf spark.driverEnv.SPARK_HOME=/opt/spark --conf spark.executorEnv.SPARK_HOME=/opt/spark --conf spark.driverEnv.PATH=/opt/spark/bin:/usr/local/bin:/usr/bin:$PATH --conf spark.executorEnv.PATH=/opt/spark/bin:/usr/local/bin:/usr/bin:$PATH --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.4,org.postgresql:postgresql:42.6.0 --executor-memory 2G --driver-memory 1G --name Spark Csv To Postgres Teams --queue root.default --deploy-mode client /opt/***/include/scripts/spark_csv_to_postgres_teams.py. Error code is: 1.
[2025-01-07T13:19:05.391+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline, task_id=spark_csv_to_postgres_teams, execution_date=20250107T131343, start_date=20250107T131856, end_date=20250107T131905
[2025-01-07T13:19:05.456+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 388 for task spark_csv_to_postgres_teams (Cannot execute: spark-submit --master spark-master:7077 --conf spark.executor.extraJavaOptions=-Dlog4j.configuration=log4j.properties --conf spark.driverEnv.SPARK_HOME=/opt/spark --conf spark.executorEnv.SPARK_HOME=/opt/spark --conf spark.driverEnv.PATH=/opt/spark/bin:/usr/local/bin:/usr/bin:$PATH --conf spark.executorEnv.PATH=/opt/spark/bin:/usr/local/bin:/usr/bin:$PATH --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.4,org.postgresql:postgresql:42.6.0 --executor-memory 2G --driver-memory 1G --name Spark Csv To Postgres Teams --queue root.default --deploy-mode client /opt/***/include/scripts/spark_csv_to_postgres_teams.py. Error code is: 1.; 58)
[2025-01-07T13:19:05.476+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-01-07T13:19:05.554+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
