[2024-12-29T05:54:57.372+0000] {processor.py:157} INFO - Started process (PID=30) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:54:57.375+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T05:54:57.378+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:54:57.377+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:54:57.390+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:54:57.387+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/initialize_postgres_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/initialize_postgres_db.py", line 4, in <module>
    from create_tables import create_database, create_tables  # Import your functions
ModuleNotFoundError: No module named 'create_tables'
[2024-12-29T05:54:57.393+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:54:57.442+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.076 seconds
[2024-12-29T05:55:27.681+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:55:27.682+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T05:55:27.683+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:55:27.683+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:55:27.695+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:55:27.693+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/initialize_postgres_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/initialize_postgres_db.py", line 4, in <module>
    from create_tables import create_database, create_tables  # Import your functions
ModuleNotFoundError: No module named 'create_tables'
[2024-12-29T05:55:27.698+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:55:27.724+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.048 seconds
[2024-12-29T05:55:58.013+0000] {processor.py:157} INFO - Started process (PID=34) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:55:58.014+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T05:55:58.015+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:55:58.015+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:55:58.024+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:55:58.023+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/initialize_postgres_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/initialize_postgres_db.py", line 4, in <module>
    from create_tables import create_database, create_tables  # Import your functions
ModuleNotFoundError: No module named 'create_tables'
[2024-12-29T05:55:58.024+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:55:58.041+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.031 seconds
[2024-12-29T05:56:28.390+0000] {processor.py:157} INFO - Started process (PID=36) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:56:28.392+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T05:56:28.394+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:56:28.393+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:56:28.406+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:56:28.404+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/initialize_postgres_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/initialize_postgres_db.py", line 4, in <module>
    from create_tables import create_database, create_tables  # Import your functions
ModuleNotFoundError: No module named 'create_tables'
[2024-12-29T05:56:28.408+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:56:28.432+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.046 seconds
[2024-12-29T05:56:58.652+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:56:58.653+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T05:56:58.653+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:56:58.653+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:56:58.661+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:56:58.659+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/initialize_postgres_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/initialize_postgres_db.py", line 4, in <module>
    from create_tables import create_database, create_tables  # Import your functions
ModuleNotFoundError: No module named 'create_tables'
[2024-12-29T05:56:58.661+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:56:58.678+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.029 seconds
[2024-12-29T05:57:29.014+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:57:29.016+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T05:57:29.017+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:57:29.016+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:57:29.023+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:57:29.021+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/initialize_postgres_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/initialize_postgres_db.py", line 4, in <module>
    from create_tables import create_database, create_tables  # Import your functions
ModuleNotFoundError: No module named 'create_tables'
[2024-12-29T05:57:29.024+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:57:29.047+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.038 seconds
[2024-12-29T05:57:59.296+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:57:59.297+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T05:57:59.298+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:57:59.298+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:57:59.307+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:57:59.304+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/initialize_postgres_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/initialize_postgres_db.py", line 4, in <module>
    from create_tables import create_database, create_tables  # Import your functions
ModuleNotFoundError: No module named 'create_tables'
[2024-12-29T05:57:59.308+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:57:59.327+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.035 seconds
[2024-12-29T05:58:29.616+0000] {processor.py:157} INFO - Started process (PID=44) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:58:29.619+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T05:58:29.621+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:58:29.620+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:58:29.634+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:58:29.632+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/initialize_postgres_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/initialize_postgres_db.py", line 4, in <module>
    from create_tables import create_database, create_tables  # Import your functions
ModuleNotFoundError: No module named 'create_tables'
[2024-12-29T05:58:29.636+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:58:29.667+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.060 seconds
[2024-12-29T05:58:59.919+0000] {processor.py:157} INFO - Started process (PID=46) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:58:59.922+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T05:58:59.924+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:58:59.923+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:58:59.932+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:58:59.931+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/initialize_postgres_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/initialize_postgres_db.py", line 4, in <module>
    from create_tables import create_database, create_tables  # Import your functions
ModuleNotFoundError: No module named 'create_tables'
[2024-12-29T05:58:59.933+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:58:59.954+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.039 seconds
[2024-12-29T05:59:30.261+0000] {processor.py:157} INFO - Started process (PID=48) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:59:30.263+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T05:59:30.264+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:59:30.264+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:59:30.275+0000] {logging_mixin.py:150} INFO - [2024-12-29T05:59:30.274+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/initialize_postgres_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/initialize_postgres_db.py", line 4, in <module>
    from create_tables import create_database, create_tables  # Import your functions
ModuleNotFoundError: No module named 'create_tables'
[2024-12-29T05:59:30.275+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T05:59:30.298+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.044 seconds
[2024-12-29T06:00:00.644+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:00:00.647+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T06:00:00.649+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:00:00.649+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:00:00.663+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:00:00.660+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/initialize_postgres_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/initialize_postgres_db.py", line 4, in <module>
    from create_tables import create_database, create_tables  # Import your functions
ModuleNotFoundError: No module named 'create_tables'
[2024-12-29T06:00:00.664+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:00:00.696+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.061 seconds
[2024-12-29T06:00:31.021+0000] {processor.py:157} INFO - Started process (PID=52) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:00:31.024+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T06:00:31.027+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:00:31.026+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:00:31.050+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:00:31.048+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/initialize_postgres_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/initialize_postgres_db.py", line 4, in <module>
    from create_tables import create_database, create_tables  # Import your functions
ModuleNotFoundError: No module named 'create_tables'
[2024-12-29T06:00:31.051+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:00:31.081+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.069 seconds
[2024-12-29T06:00:40.118+0000] {processor.py:157} INFO - Started process (PID=53) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:00:40.120+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T06:00:40.120+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:00:40.120+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:00:40.146+0000] {processor.py:836} INFO - DAG(s) dict_keys(['initialize_postgres_db']) retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:00:40.301+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:00:40.300+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-12-29T06:00:40.316+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:00:40.316+0000] {dag.py:3508} INFO - Setting next_dagrun for initialize_postgres_db to None, run_after=None
[2024-12-29T06:00:40.330+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.215 seconds
[2024-12-29T06:01:10.702+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:01:10.703+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T06:01:10.703+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:01:10.703+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:01:10.721+0000] {processor.py:836} INFO - DAG(s) dict_keys(['initialize_postgres_db']) retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:01:10.752+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:01:10.752+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-12-29T06:01:10.787+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:01:10.787+0000] {dag.py:3508} INFO - Setting next_dagrun for initialize_postgres_db to None, run_after=None
[2024-12-29T06:01:10.806+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.110 seconds
[2024-12-29T06:01:41.027+0000] {processor.py:157} INFO - Started process (PID=57) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:01:41.030+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T06:01:41.031+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:01:41.030+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:01:41.047+0000] {processor.py:836} INFO - DAG(s) dict_keys(['initialize_postgres_db']) retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:01:41.077+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:01:41.077+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-12-29T06:01:41.095+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:01:41.095+0000] {dag.py:3508} INFO - Setting next_dagrun for initialize_postgres_db to None, run_after=None
[2024-12-29T06:01:41.105+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.083 seconds
[2024-12-29T06:02:11.395+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:02:11.396+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T06:02:11.397+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:02:11.397+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:02:11.414+0000] {processor.py:836} INFO - DAG(s) dict_keys(['initialize_postgres_db']) retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:02:11.444+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:02:11.444+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-12-29T06:02:11.460+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:02:11.460+0000] {dag.py:3508} INFO - Setting next_dagrun for initialize_postgres_db to None, run_after=None
[2024-12-29T06:02:11.470+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.078 seconds
[2024-12-29T06:02:41.741+0000] {processor.py:157} INFO - Started process (PID=61) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:02:41.743+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T06:02:41.745+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:02:41.744+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:02:41.765+0000] {processor.py:836} INFO - DAG(s) dict_keys(['initialize_postgres_db']) retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:02:41.800+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:02:41.800+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-12-29T06:02:41.818+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:02:41.817+0000] {dag.py:3508} INFO - Setting next_dagrun for initialize_postgres_db to None, run_after=None
[2024-12-29T06:02:41.828+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.091 seconds
[2024-12-29T06:03:12.088+0000] {processor.py:157} INFO - Started process (PID=63) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:03:12.091+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T06:03:12.092+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:03:12.091+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:03:12.112+0000] {processor.py:836} INFO - DAG(s) dict_keys(['initialize_postgres_db']) retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:03:12.156+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:03:12.155+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-12-29T06:03:12.182+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:03:12.182+0000] {dag.py:3508} INFO - Setting next_dagrun for initialize_postgres_db to None, run_after=None
[2024-12-29T06:03:12.193+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.110 seconds
[2024-12-29T06:03:42.351+0000] {processor.py:157} INFO - Started process (PID=65) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:03:42.353+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T06:03:42.354+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:03:42.354+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:03:42.377+0000] {processor.py:836} INFO - DAG(s) dict_keys(['initialize_postgres_db']) retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:03:42.409+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:03:42.409+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-12-29T06:03:42.426+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:03:42.426+0000] {dag.py:3508} INFO - Setting next_dagrun for initialize_postgres_db to None, run_after=None
[2024-12-29T06:03:42.437+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.091 seconds
[2024-12-29T06:04:12.611+0000] {processor.py:157} INFO - Started process (PID=67) to work on /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:04:12.613+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/initialize_postgres_db.py for tasks to queue
[2024-12-29T06:04:12.614+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:04:12.614+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:04:12.627+0000] {processor.py:836} INFO - DAG(s) dict_keys(['initialize_postgres_db']) retrieved from /opt/airflow/dags/initialize_postgres_db.py
[2024-12-29T06:04:12.650+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:04:12.650+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-12-29T06:04:12.664+0000] {logging_mixin.py:150} INFO - [2024-12-29T06:04:12.664+0000] {dag.py:3508} INFO - Setting next_dagrun for initialize_postgres_db to None, run_after=None
[2024-12-29T06:04:12.674+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/initialize_postgres_db.py took 0.068 seconds
