[2025-01-06T13:23:25.540+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.fetch_and_send_active_players manual__2025-01-06T13:18:30.603707+00:00 [queued]>
[2025-01-06T13:23:25.545+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.fetch_and_send_active_players manual__2025-01-06T13:18:30.603707+00:00 [queued]>
[2025-01-06T13:23:25.545+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2025-01-06T13:23:25.555+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): fetch_and_send_active_players> on 2025-01-06 13:18:30.603707+00:00
[2025-01-06T13:23:25.561+0000] {standard_task_runner.py:57} INFO - Started process 1889 to run task
[2025-01-06T13:23:25.563+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'fetch_and_send_active_players', 'manual__2025-01-06T13:18:30.603707+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/full_nba_data_pipeline copy.py', '--cfg-path', '/tmp/tmp2falln84']
[2025-01-06T13:23:25.567+0000] {standard_task_runner.py:85} INFO - Job 253: Subtask fetch_and_send_active_players
[2025-01-06T13:23:25.688+0000] {task_command.py:410} INFO - Running <TaskInstance: nba_data_pipeline.fetch_and_send_active_players manual__2025-01-06T13:18:30.603707+00:00 [running]> on host ccc35606ded5
[2025-01-06T13:23:25.729+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_send_active_players' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T13:18:30.603707+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T13:18:30.603707+00:00'
[2025-01-06T13:26:07.657+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-01-06T13:26:07.670+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 1889. PIDs of all processes in the group: [1889]
[2025-01-06T13:26:07.671+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 1889
[2025-01-06T13:27:07.681+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=1889, name='airflow task ru', status='sleeping', started='13:23:24') did not respond to SIGTERM. Trying SIGKILL
[2025-01-06T13:27:07.696+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 1889
[2025-01-06T13:27:07.717+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1889, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='13:23:24') (1889) terminated with exit code Negsignal.SIGKILL
[2025-01-06T13:27:07.719+0000] {standard_task_runner.py:174} ERROR - Job 253 was killed before it finished (likely due to running out of memory)
